modLoader="javafml"
loaderVersion="${loader_version}"
issueTrackerURL="https://github.com/lehjr/MachineMusePowersuits/issues"
license="All rights reserved"
[[mods]]
    modId="numina"
    version="${version}"
    displayName="Numina"
    updateJSONURL="https://mc-curse-update-checker.herokuapp.com/235440"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/numina"
    authors="MachineMuse, lehjr"
    description="A common library of useful functions and utilities for dealing with Minecraft's source code."

[[dependencies.numina]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    side="BOTH"

[[dependencies.numina]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version}"
    side="BOTH"

[[dependencies.numina]]
    modId="jei"
    mandatory=false
    versionRange="${jei_version}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.numina]]
    modId="appliedenergistics2"
    mandatory=false
    versionRange="[${ae2_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.numina]]
    modId="scannable"
    mandatory=false
    versionRange="[${scannable_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.numina]]
    modId="refinedstorage"
    mandatory=false
    versionRange="${refinedstorage_version}"
    ordering="AFTER"
    side="BOTH"