modLoader="javafml"
loaderVersion="${loader_version}"
issueTrackerURL="https://github.com/lehjr/MachineMusePowersuits/issues"
license="All rights reserved"

[[mods]]
    modId="powersuits"
    version="${version}"
    displayName="MachineMuse's Modular Powersuits"
    updateJSONURL="https://mc-curse-update-checker.herokuapp.com/235442"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/modular-powersuits"
    authors="MachineMuse, lehjr"
    credits="Icons by WaterCandle, Modeling by SebK"
    logoFile="logo.png"
    description='''
A mod which adds modular power armor, power tool, and a tinker table to configure them. Uses FE (Foreg Energy), EU (IndustrialCraft 2) or RF (Thermal Expansion 4).
'''

[[dependencies.powersuits]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    side="BOTH"

[[dependencies.powersuits]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version}"
    side="BOTH"

[[dependencies.powersuits]]
    modId="numina"
    mandatory=true
    versionRange="[${version}]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.powersuits]]
    modId="appliedenergistics2"
    mandatory=false
    versionRange="[${ae2_version},)"
    ordering="AFTER"
    side="BOTH"